House_Renting_Solver/House_Renting_Solver/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('update/', user_views.update, name='update'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

House_Renting_Solver/blog/urls.py
from django.urls import path
from .views import PostDetailView, PostUpdateView, PostDeleteView, UserPostListView,UserProfileView
from . import views

urlpatterns = [
     
     path('', views.home, name='template-home'),
     path('home/', views.PostList1, name='blog-home'),
     path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
     path('post/<str:username>', UserProfileView.as_view(), name='user-profile'),
     path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
     #path('post/new/', PostCreateView.as_view(), name='post-create'),
     path('post/new/', views.PostCreate, name='post-create'),
     path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
     path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
#    path('', views.home, name='blog-home'),
     path('about/', views.about, name='blog-about'),
]

House_Renting_Solver/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):

    location = models.CharField(max_length = 100)
    content = models.TextField()
    date_posted = models.DateTimeField(default = timezone.now)
    owner = models.ForeignKey(User, on_delete= models.CASCADE)


    def __str__(self):
        return self.location

    def get_absolute_url(self):
      return reverse('post-detail', kwargs={'pk': self.pk})

HOUSE_CHOICES = (
    ('one','Flat'),
    ('two','Seat'),
    ('three','Sub-let'),
    ('four','mess'),
    ('five','hostel'),
)

RENTER_CHOICES = (
    ('one','Family'),
    ('two','Bachelor'),
    ('three','Working Man'),
    ('four','Working Woman'),
    ('five','Anyone'),
)
MEMBER_CHOICES = (
    ('zero','0'),
    ('one','1'),
    ('two','2'),
    ('three','3'),
    ('four','4'),
    ('five','5'),
    ('six','6'),
    ('seven','7'),
    ('eight','8'),
)
RELIGION_CHOICES = (
    ('one','Islam'),
    ('two','Hinduism'),
    ('three','Christianity'),
    ('four','Buddism'),
    ('five','Anyone')
)
OCCUPATION_CHOICES = (
    ('one','Service Holder'),
    ('two','Business Man'),
    ('three','Students'),
    ('five','Anyone')
)
BED_CHOICES = (
    ('zero','0'),
    ('one','1'),
    ('two','2'),
    ('three','3'),
    ('four','4'),
    ('five','5')
)

FACILITY_CHOICES = (
    ('one','Yes'),
    ('two','No'),
)

GAS_CHOICES = (
    ('one','Pipeline'),
    ('two','Cylinder')
)
FLOOR_CHOICES = (
    ('zero','0'),
    ('one','1'),
    ('two','2'),
    ('three','3'),
    ('four','4'),
    ('five','5'),
    ('six','6'),
    ('seven','7'),
    ('eight','8'),
    ('nine','9'),
    ('ten','10'),
)

class Post3(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    house_type = models.CharField(max_length=5,choices=HOUSE_CHOICES)
    renter_preference = models.CharField(max_length=5,choices=RENTER_CHOICES)
    family_member = models.CharField(max_length=5,choices=MEMBER_CHOICES)
    religion_preference = models.CharField(max_length=5,choices=RELIGION_CHOICES)
    occupation_priority = models.CharField(max_length=5,choices=OCCUPATION_CHOICES)
    address = models.CharField(max_length=150)
    floor = models.CharField(max_length=10,choices=FLOOR_CHOICES)
    bed_room = models.CharField(max_length=5,choices=BED_CHOICES)
    bed_room_image = models.ImageField(upload_to='profile_pics',null=True,blank=True)
    drawing_room = models.CharField(max_length=5,choices=BED_CHOICES)
    drawing_room_image = models.ImageField(upload_to='profile_pics',null=True,blank=True)
    dinning_room = models.CharField(max_length=5,choices=BED_CHOICES)
    dinning_room_image = models.ImageField(upload_to='profile_pics',null=True,blank=True)
    kitchen = models.CharField(max_length=5,choices=BED_CHOICES)
    kitchen_room_image = models.ImageField(upload_to='profile_pics',null=True,blank=True)
    bathroom = models.CharField(max_length=5,choices=BED_CHOICES)
    bath_room_image = models.ImageField(upload_to='profile_pics',null=True,blank=True)
    washing_Machine = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    hot_water = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    IPS = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Generator = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Belcony = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Oven = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    lift = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    refrigerator = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    sofa = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    wifi = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    ac = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    television = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    gas = models.CharField(max_length=3,choices=GAS_CHOICES)
    security = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    parking = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    house_rent = models.CharField(max_length=10)
    electricity_rent = models.CharField(max_length=5,null=True)
    gas_rent = models.CharField(max_length=5,null=True)
    water_rent = models.CharField(max_length=5,null=True)
    service_rent = models.CharField(max_length=5,null=True)
    rent_date = models.DateTimeField()
    any_special_instructions = models.TextField()

    def __str__(self):
        return self.owner.username

    def get_absolute_url(self):
      return reverse('post-detail', kwargs={'pk': self.pk})



class Post1(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    house_type = models.CharField(max_length=5,choices=HOUSE_CHOICES)
    renter_preference = models.CharField(max_length=5,choices=RENTER_CHOICES)
    family_member = models.CharField(max_length=5,choices=MEMBER_CHOICES)
    religion_preference = models.CharField(max_length=5,choices=RELIGION_CHOICES)
    occupation_priority = models.CharField(max_length=5,choices=OCCUPATION_CHOICES)
    address = models.CharField(max_length=150)
    bed_room = models.CharField(max_length=5,choices=BED_CHOICES)
    bed_room_image = models.ImageField(upload_to='profile_pics')
    drawing_room = models.CharField(max_length=5,choices=BED_CHOICES)
    drawing_room_image = models.ImageField(upload_to='profile_pics')
    dinning_room = models.CharField(max_length=5,choices=BED_CHOICES)
    dinning_room_image = models.ImageField(upload_to='profile_pics')
    kitchen = models.CharField(max_length=5,choices=BED_CHOICES)
    kitchen_room_image = models.ImageField(upload_to='profile_pics')
    bathroom = models.CharField(max_length=5,choices=BED_CHOICES)
    bath_room_image = models.ImageField(upload_to='profile_pics')
    washing_Machine = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    hot_water = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    IPS = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Generator = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Belcony = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Oven = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    lift = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    refrigerator = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    sofa = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    wifi = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    ac = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    television = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    gas = models.CharField(max_length=3,choices=GAS_CHOICES)
    security = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    parking = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    house_rent = models.CharField(max_length=10)
    electricity_rent = models.CharField(max_length=5,null=True)
    gas_rent = models.CharField(max_length=5,null=True)
    water_rent = models.CharField(max_length=5,null=True)
    service_rent = models.CharField(max_length=5,null=True)
    any_special_instructions = models.TextField()

    def __str__(self):
        return self.owner.username

    def get_absolute_url(self):
      return reverse('post-detail', kwargs={'pk': self.pk})



class Post2(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    house_type = models.CharField(max_length=5,choices=HOUSE_CHOICES)
    renter_preference = models.CharField(max_length=5,choices=RENTER_CHOICES)
    family_member = models.CharField(max_length=5,choices=MEMBER_CHOICES)
    religion_preference = models.CharField(max_length=5,choices=RELIGION_CHOICES)
    occupation_priority = models.CharField(max_length=5,choices=OCCUPATION_CHOICES)
    address = models.CharField(max_length=150)
    floor = models.CharField(max_length=10,choices=FLOOR_CHOICES)
    bed_room = models.CharField(max_length=5,choices=BED_CHOICES)
    bed_room_image = models.ImageField(upload_to='profile_pics')
    drawing_room = models.CharField(max_length=5,choices=BED_CHOICES)
    drawing_room_image = models.ImageField(upload_to='profile_pics')
    dinning_room = models.CharField(max_length=5,choices=BED_CHOICES)
    dinning_room_image = models.ImageField(upload_to='profile_pics')
    kitchen = models.CharField(max_length=5,choices=BED_CHOICES)
    kitchen_room_image = models.ImageField(upload_to='profile_pics')
    bathroom = models.CharField(max_length=5,choices=BED_CHOICES)
    bath_room_image = models.ImageField(upload_to='profile_pics')
    washing_Machine = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    hot_water = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    IPS = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Generator = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Belcony = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    Oven = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    lift = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    refrigerator = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    sofa = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    wifi = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    ac = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    television = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    gas = models.CharField(max_length=3,choices=GAS_CHOICES)
    security = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    parking = models.CharField(max_length=3,choices=FACILITY_CHOICES)
    house_rent = models.CharField(max_length=10)

House_Renting_Solver/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')


    def __str__(self):
        return f'{self.user.username} Profile'

#    def save(self):
#        super().save()

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)


        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


GENDER_CHOICES = (
    ('one','Man'),
    ('two','Woman'),
    ('three','Others'),
)
MARITAL_CHOICES = (
    ('one','Unmarried'),
    ('two','Married'),
)

class Register(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    occupation = models.CharField(max_length = 150)
    address = models.CharField(max_length = 150)
    gender = models.CharField(max_length=5,choices=GENDER_CHOICES)
    phone = models.CharField(max_length=12, null=True)
    religion = models.CharField(max_length = 20,null=True)
    marital_status = models.CharField(max_length=3,choices=MARITAL_CHOICES)
    nid = models.CharField(max_length=11)

    def __str__(self):
        return self.user.username

House_Renting_Solver/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post1,Post3

class CreatePostForm(forms.ModelForm):
    
    class Meta:
        model = Post3
        #fields = ['bed_room_image']
        fields = ['house_type','renter_preference','family_member','religion_preference','occupation_priority',
            'address','floor','bed_room','bed_room_image','drawing_room','drawing_room_image','dinning_room','dinning_room_image','kitchen',
            'kitchen_room_image','bathroom','bath_room_image','washing_Machine','hot_water','IPS','Generator','Belcony','Oven','lift','refrigerator','sofa','wifi','ac','television','gas','security',
            'parking','house_rent','electricity_rent','gas_rent','water_rent','service_rent','rent_date','any_special_instructions']
        widgets = {
                'house_type': forms.RadioSelect(),
                'renter_preference':forms.RadioSelect(),
                'family_member':forms.RadioSelect(),
                'religion_preference':forms.RadioSelect(),
                'occupation_priority':forms.RadioSelect(),
                'floor':forms.RadioSelect(),
                'bed_room':forms.RadioSelect(),
                'drawing_room':forms.RadioSelect(),
                'dinning_room':forms.RadioSelect(),
                'kitchen':forms.RadioSelect(),
                'bathroom':forms.RadioSelect(),
                'washing_Machine':forms.RadioSelect(),
                'hot_water':forms.RadioSelect(),
                'IPS':forms.RadioSelect(),
                'Generator':forms.RadioSelect(),
                'Belcony':forms.RadioSelect(),
                'Oven':forms.RadioSelect(),
                'lift':forms.RadioSelect(),
                'refrigerator':forms.RadioSelect(),
                'sofa':forms.RadioSelect(),
                'wifi':forms.RadioSelect(),
                'ac':forms.RadioSelect(),
                'television':forms.RadioSelect(),
                'gas':forms.RadioSelect(),
                'security':forms.RadioSelect(),
                'parking':forms.RadioSelect(),
                
            }     

        
            

House_Renting_Solver/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
   <h1 class="card-header"> About this platfrom </h1>
   <div class="card-body">
   <p>
     Today many people in our country search for rental houses on foot, knocking
from door to door. Sometimes it’s really hard to get a proper rental house.
It’s very problematic and costly. It really needs a lot of time and affords.
Even it seems very hard in new places. The idea that rental houses can
be searched online is not grasped by many. Nowadays everything is getting
e-based. So why not ‘to-let’?.
   </p>
   <p>
     The idea of "House Renting Solver" solves the house searching problems in
this modern time. The project intends to solve the ‘to-let’ issue by turning
it into a web-based system. The system offers to the users a proper description of ‘to-let’ houses in his located area. Later it will also be available on
the android application.
   </p>
</div>
{% endblock content %}

House_Renting_Solver/blog/templates/blog/home1.html
{% extends "blog/base.html" %}
{% block content %}
      
    

   {% for post in page_obj %}

   <article class="media content-section">
     <img class="rounded-circle article-img" src="{{ post.owner.profile.image.url}}" >
     <div class="media-body">
         <div class="article-metadata">
             <a class="mr-2" href="{% url 'user-profile' post.owner.username %}">{{ post.owner }}</a> 
             <small class="text-muted">{{ post.date_posted|date:"D d M Y"}} {{ post.date_posted|time:"P"}}</small>
          </div>
           <div>
             
             <h3>Requirements By the Owner: </h3>

                    <!--   house_type','renter_preference','family_member','religion_preference','occupation_priority',
                        'address','floor','bed_room','bed_room_image','drawing_room','drawing_room_image','dinning_room','dinning_room_image','kitchen',
                        'kitchen_room_image','bathroom','bath_room_image','washing_Machine','hot_water','IPS','Generator','Belcony','Oven','lift','refrigerator','sofa','wifi','ac','television','gas','security',
                        'parking','house_rent','electricity_rent','gas_rent','water_rent','service_rent','rent_date','any_special_instructions'
                    --> 
            
             <table>
               <tr>
                 <th> House Type:</th>
                 <th> {{ post.get_house_type_display }} </th>
               </tr>
               <tr>
                <th> Renter Preference :</th>
                <th> {{ post.get_renter_preference_display }} </th>
              </tr>
              <tr>
                <th> Family Member :</th>
                <th> {{ post.get_family_member_display }} </th>
              </tr>
              <tr>
                <th> Religion Preference :</th>
                <th> {{ post.get_religion_preference_display }} </th>
              </tr>
              <tr>
                <th> Occupation Priority :</th>
                <th> {{ post.get_occupation_priority_display }} </th>
              </tr>
              <tr>
                <th> Address :</th>
                <th> {{ post.address }} </th>
              </tr>
              <tr>
                <th> Floor No :</th>
                <th> {{ post.get_floor_display }} </th>
              </tr>
              <tr>
                <th> Bed Room :</th>
                <th> {{ post.get_bed_room_display }} </th>
              </tr>
              <tr>
                <th> Drawing Room :</th>
                <th> {{ post.get_drawing_room_display }} </th>
              </tr>
              <tr>
                <th> Dinning Room :</th>
                <th> {{ post.get_dinning_room_display }} </th>
              </tr>
              <tr>
                <th> Kitchen :</th>
                <th> {{ post.get_kitchen_display }} </th>
              </tr>
              <tr>
                <th> Bath Room :</th>
                <th> {{ post.get_bathroom_display }} </th>
              </tr>
             </table>
             <br>
             <hr>

             <div class="article-content" > 
              <h6>For more details :  <a href = "{%url 'post-detail' post.id %}"> See More </a> </h6>
            </div>

            <!--
             <h4> Facilities: </h3> -->
               <!--   house_type','renter_preference','family_member','religion_preference','occupation_priority',
            'address','floor','bed_room','bed_room_image','drawing_room','drawing_room_image','dinning_room','dinning_room_image','kitchen',
            'kitchen_room_image','bathroom','bath_room_image','washing_Machine','hot_water','IPS','Generator','Belcony','Oven','lift','refrigerator','sofa','wifi','ac','television','gas','security',
            'parking','house_rent','electricity_rent','gas_rent','water_rent','service_rent','rent_date','any_special_instructions'
               -->

               <!--
              <table>
                <tr>
                  <th> Washing Machine :</th>
                  <th> {{ post.get_washing_Machine_display }} </th>
                </tr>
                <tr>
                  <th> Hot Water :</th>
                  <th> {{ post.get_hot_water_display }} </th>
                </tr>
                <tr>
                  <th> IPS :</th>
                  <th> {{ post.get_IPS_display }} </th>
                </tr>
                <tr>
                  <th> Generator :</th>
                  <th> {{ post.get_Generator_display }} </th>
                </tr>
                <tr>
                  <th> Oven :</th>
                  <th> {{ post.get_Oven_display }} </th>
                </tr>
                <tr>
                  <th> Belcony :</th>
                  <th> {{ post.get_Belcony_display }} </th>
                </tr>
                <tr>
                  <th> Lift :</th>
                  <th> {{ post.get_lift_display }} </th>
                </tr>
                <tr>
                  <th> Refrigerator :</th>
                  <th> {{ post.get_refrigerator_display }} </th>
                </tr>
                <tr>
                  <th> Sofa :</th>
                  <th> {{ post.get_sofa_display }} </th>
                </tr>
                <tr>
                  <th> Wifi :</th>
                  <th> {{ post.get_wifi_display }} </th>
                </tr>
                <tr>
                  <th> AC :</th>
                  <th> {{ post.get_ac_display }} </th>
                </tr>
                <tr>
                  <th> Television :</th>
                  <th> {{ post.get_television_display }} </th>
                </tr>
                <tr>
                  <th> Gas :</th>
                  <th> {{ post.get_gas_display }} </th>
                </tr>
                <tr>
                  <th> Security :</th>
                  <th> {{ post.get_security_display }} </th>
                </tr>
                <tr>
                  <th> Parking :</th>
                  <th> {{ post.get_parking_display }} </th>
                </tr>
              </table>
              <hr>
              <h4>Bills:</h4>
              <table>
                <tr>
                  <th> House Rent :</th>
                  <th> {{ post.house_rent }} </th>
                </tr>
                <tr>

                  <th> Electricity Rent :</th>
                  <th> {{ post.electricity_rent }} </th>
                </tr>
                <tr>
                  <th> Gas Rent :</th>
                  <th> {{ post.gas_rent }} </th>
                </tr>
                <tr>
                  <th> Water Rent :</th>
                  <th> {{ post.water_rent }} </th>
                </tr>
                <tr>
                  <th> Service Rent :</th>
                  <th> {{ post.service_rent }} </th>
                </tr>
                <tr>
                  <th>  Rent Date :</th>
                  <th> {{ post.rent_date }} </th>
                </tr>
                <tr>
                  <th>  Special Announcement :</th>
                  <th> {{ post.any_special_instructions }} </th>
                </tr>
              </table> -->
           </div>
           <!--
           <hr>
           <br>
           <h4> All Images: </h4>
           <div>
              {% if post.bed_room_image %}
              <strong>Bed Room </strong>
              <img src="{{ post.bed_room_image.url}}" >
              {% endif %}
           </div>
           <hr>
           <br>
          
           <div>
              {% if post.drawing_room_image %}
              <strong>Drawing Room </strong>
              <img src="{{ post.drawing_room_image.url}}" >
              {% endif %}
           </div>
           <hr>
           <br>

           <div>
            {% if post.dinning_room_image %}
            <strong>Dinning Room </strong>
            <img src="{{ post.dinning_room_image.url}}" >
            {% endif %}
           </div>
           <hr>
           <br>
           
           <div>
            {% if post.kitchen_room_image %}
            <strong>Kitchen </strong>
            <img src="{{ post.kitchen_room_image.url}}" >
            {% endif %}
           </div>
           <hr>
           
           <br>

           <div>
            {% if post.bath_room_image %}
            <strong>Bath Room </strong>
            <img src="{{ post.bath_room_image.url}}" >
            {% endif %}
           </div>  
         </div> -->
     </article> 

   {% endfor %}
   
    
   <div class="pagination">
       <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo;&nbsp; first &nbsp;</a>
              <a href="?page={{ page_obj.previous_page_number }}">&nbsp;previous &nbsp;</a> 
          {% endif %}

          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>

          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">&nbsp;next &nbsp;</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">&nbsp;last &raquo;&nbsp;</a>
          {% endif %}
       </span>
   </div>

{% endblock content %}

House_Renting_Solver/blog/templates/blog/post1_detail.html
{% extends "blog/base.html" %}
{% block content %}
   <article class="media content-section">
     <img class="rounded-circle article-img" src="{{ object.owner.profile.image.url}}" >
     <div class="media-body">
       <div class="article-metadata">
             <a class="mr-2" href="{% url 'user-posts' object.owner.username %}">{{object.owner }}</a>
             <h1>{{ object.get_house_type_display }}</h1>
             <h1> {{ object.get_renter_preference_display }} </h1>
             {% if object.owner == user %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
                </div>
             {% endif %}
           </div>
         </div>
       </article>
{% endblock content %}

House_Renting_Solver/blog/templates/blog/post1_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class = "border-bottom mb-4">House Renting Post</legend>
              {{ form | crispy }}
          </fieldset>
            <div class="form-group">
              <button class ="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>

{% endblock content %}

House_Renting_Solver/blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
    <h4 class="mb-3">Posts by {{view.kwargs.username}}</h4>
    <h5> {{view.kwargs.username}}'s Total Post = {{ page_obj.paginator.count}} </h5>
   {% for post in post3s %}

   <article class="media content-section">
     <img class="rounded-circle article-img" src="{{ post.owner.profile.image.url}}" >

            <div class="media-body">
                  <div class="article-metadata">

                    <a class="mr-2" href="{% url 'user-profile' post.owner.username %}">{{ post.owner }}</a>
                    <small class="text-muted">{{ post.date_posted | date:"d F, Y" }}</small>
                  </div>


               <h5><a class="article-title" href="{% url 'post-detail' post.id %}">House Type: {{ post.get_house_type_display }}<br> Location: {{ post.address }} </a></h5>
            </div>
     </article>

   {% endfor %}
   {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}