House_Renting_Solver/House_Renting_Solver/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('update/', user_views.update, name='update'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('', include('blog.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

House_Renting_Solver/blog/urls.py
from django.urls import path
from .views import PostDetailView, PostUpdateView, PostDeleteView, UserPostListView,UserProfileView
from . import views

urlpatterns = [
     
     path('', views.home, name='template-home'),
     path('home/', views.PostList1, name='blog-home'),
     path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
     path('post/<str:username>', UserProfileView.as_view(), name='user-profile'),
     path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
     #path('post/new/', PostCreateView.as_view(), name='post-create'),
     path('post/new/', views.PostCreate, name='post-create'),
     path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
     path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
#    path('', views.home, name='blog-home'),
     path('about/', views.about, name='blog-about'),
]

House_Renting_Solver/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')


    def __str__(self):
        return f'{self.user.username} Profile'

#    def save(self):
#        super().save()

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)


        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


GENDER_CHOICES = (
    ('one','Man'),
    ('two','Woman'),
    ('three','Others'),
)
MARITAL_CHOICES = (
    ('one','Unmarried'),
    ('two','Married'),
)

class Register(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    occupation = models.CharField(max_length = 150)
    address = models.CharField(max_length = 150)
    gender = models.CharField(max_length=5,choices=GENDER_CHOICES)
    phone = models.CharField(max_length=12, null=True)
    religion = models.CharField(max_length = 20,null=True)
    marital_status = models.CharField(max_length=3,choices=MARITAL_CHOICES)
    nid = models.CharField(max_length=11)

    def __str__(self):
        return self.user.username

House_Renting_Solver/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile,Register

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name' ,'email','password1','password2']

class UserRegistrationForm(forms.ModelForm):

    class Meta:
        model = Register
        fields = ['occupation','address','gender','phone','religion','marital_status','nid']
        widgets = {
            'gender': forms.RadioSelect(),
            'marital_status': forms.RadioSelect()
        }

class UserUpdateForm(forms.ModelForm):
   email = forms.EmailField()

   class Meta:
        model = User
        fields = ['username','first_name','last_name', 'email']

class UserRegistrationUpdateForm(forms.ModelForm):

    class Meta:
        model = Register
        fields = ['occupation','address','gender','phone','religion','marital_status','nid']
        widgets = {
            'gender': forms.RadioSelect(),
            'marital_status': forms.RadioSelect()
        }

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

House_Renting_Solver/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm,UserRegistrationForm,UserRegistrationUpdateForm
from .models import Register
from django.core import serializers

def register(request):
    if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            form1 = UserRegistrationForm(request.POST)
            if  form.is_valid() and form1.is_valid():
                user = form.save()
                user.save()
                register = form1.save(commit=False)
                register.user = user
                register.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f'Your account has been created! You are now able to log in!')
                return redirect('login')
    else:
         form = UserRegisterForm(request.POST)
         form1 = UserRegistrationForm(request.POST)
    return render(request, 'users/register.html', {'form': form,'form1':form1})

@login_required
def profile(request):
    user = request.user
    context = {
        'register': Register.objects.all()
    }
    template = 'users/profile.html'
    return render(request,template,context)



@login_required
def update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance = request.user)
        v_form = UserRegistrationUpdateForm(request.POST,request.FILES,instance=request.user.register)
        p_form = ProfileUpdateForm(request.POST,
        request.FILES,
        instance = request.user.profile)

        if u_form.is_valid() or v_form.is_valid() or p_form.is_valid():
            u_form.save()
            v_form.save()
            p_form.save()
            messages.success(request,f'Your account has been updated')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance = request.user)
        v_form = UserRegistrationUpdateForm(instance=request.user.register)
        p_form = ProfileUpdateForm(instance = request.user.profile)
    context = {
        'u_form':u_form,
        'v_form':v_form,
        'p_form':p_form
    }
    return render(request,'users/update.html',context)

House_Renting_Solver/users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class = "border-bottom mb-4">Log In</legend>
              {{ form | crispy }}
          </fieldset>
    <div class="form-group">
       <button class ="btn btn-outline-info" type="submit">Login</button>
       <small class="test-muted ml-2">
            <a href="{% url 'password_reset' %}">Forget Password?</a>
       </small>
    </div>
        </form>
    <div class="border-top pt-3">
          <small class="text-muted">
               Need An Account? <a class="ml-2" href="{% url 'register' %}"> Sign Up Now</a>
          </small>
    </div>
    </div>

{% endblock content %}

House_Renting_Solver/users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}

      <h3>You have been logged out</h3>
    <div class="border-top pt-3">
          <small class="text-muted">
            <a  href="{% url 'login' %}"> Log In Again</a>
          </small>
    </div>


{% endblock content %}

House_Renting_Solver/users/templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class = "border-bottom mb-4">Reset Password</legend>
              {{ form | crispy }}
          </fieldset>
    <div class="form-group">
       <button class ="btn btn-outline-info" type="submit">Request Password Reset</button>
    </div>
        </form>
    </div>

{% endblock content %}

House_Renting_Solver/users/templates/users/password_reset_complete.html
{% extends "blog/base.html" %}
{% block content %}

     <div class="alert alert-info">
        Your password has been set.
     </div>
     <a href="{% url 'login' %}">Sign In Here</a>

{% endblock content %}

House_Renting_Solver/users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class = "border-bottom mb-4">Reset Password</legend>
              {{ form | crispy }}
          </fieldset>
    <div class="form-group">
       <button class ="btn btn-outline-info" type="submit">Reset Password</button>
    </div>
        </form>
    </div>

{% endblock content %}

House_Renting_Solver/users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}

     <div class="alert alert-info">
        An email has been sent with instructions to reset your password
     </div>

{% endblock content %}

House_Renting_Solver/users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<!-- 'occupation','address','gender','phone','religion','marital_status','nid' -->
{% for post in register %}

  {% if post.user.username == user.username %}
      <div class="content-section">
        <div class="media">
          <img class="rounded-circle account-img" src="{{user.profile.image.url}}">
            <h2 class="account-heading">{{user.username }}</h2>

              <fieldset class="form-group">
                <legend class = "border-bottom mb-4">Profile Information</legend>
                
            </fieldset>
              <div class="media-body">
                <!--
                <div>
                 <strong> <h5> Name : {{ user.first_name }} {{ user.last_name }}</h5> </strong> 
                </div>
                <div>
                  <strong> <h5> E-mail : {{ user.email }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> Occupation : {{ post.occupation }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> Address : {{ post.address }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> Gender : {{ post.get_gender_display }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> Contact : {{ post.phone }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> Religion : {{ post.religion }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> Marital Status : {{ post.get_marital_status_display }}</h5> </strong> 
                 </div>
                 <div>
                  <strong> <h5> National Id : {{ post.nid }}</h5> </strong> 
                 </div>

                 <form>
                  <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" value="{{ user.email }}">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                  </div>
                 </form> -->

                 <form class="row g-3">

                  <div class="col-md-6">
                    <label for="inputEmail4" class="form-label"> <strong> Name </strong></label>
                    <input type="email" class="form-control" id="inputEmail4" value = "{{ user.first_name }} {{ user.last_name }}">
                  </div>

                  <div class="col-md-6">
                    <label for="inputEmail4" class="form-label">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" value = "{{ user.email }}">
                  </div>

  
                  <div class="col-12">
                    <label for="inputAddress" class="form-label">Address</label>
                    <input type="text" class="form-control" id="inputAddress" value="{{post.address}}">
                  </div>

                  <div class="col-12">
                    <label for="inputAddress" class="form-label">Occupation</label>
                    <input type="text" class="form-control" id="inputAddress" value="{{post.occupation}}">
                  </div>

                  <div class="col-12">
                    <label for="inputAddress2" class="form-label">Contact Number </label>
                    <input type="text" class="form-control" id="inputAddress2" value = "{{ post.phone }}">
                  </div>
                  <div class="col-md-6">
                    <label for="inputCity" class="form-label"> Gender </label>
                    <input type="text" class="form-control" id="inputCity" value="{{ post.get_gender_display }}">
                  </div>
                  <div class="col-md-6">
                    <label for="inputState" class="form-label">Religion</label>
                    <input type="text" class="form-control" id="inputCity" value="{{ post.religion }}">
                  </div>

                  <div class="col-md-6">
                    <label for="inputCity" class="form-label"> Marital Status  </label>
                    <input type="text" class="form-control" id="inputCity" value="{{ post.get_marital_status_display }}">
                  </div>
                  <div class="col-md-6">
                    <label for="inputState" class="form-label">National Id </label>
                    <input type="text" class="form-control" id="inputCity" value="{{ post.nid }}">
                  </div>
                </form>
                <br>
                

                <div class = "form-group">
                  <button type="button" class="btn btn-outline-dark" ><a class="mr-2" href="{% url 'user-posts' post.user.username %}">All Posts</a> </button>
                </div>
                <br>
                <div class = "form-group">
                  <button class = "btn btn-outline-info" type="submit"> <a class="mr-2" href="{% url 'update' %}">Update Profile </a> </button>
                </div>


              </div>
        </div>
      </div>
  {% endif %}

{% endfor %}



{% endblock content %}

House_Renting_Solver/users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
          {% csrf_token %}
               
          <fieldset class="form-group">
              <legend class = "border-bottom mb-4">Join Today</legend>
              {{ form | crispy }}
              {{ form1| crispy }}
          </fieldset>
    <div class="form-group">
       <button class ="btn btn-outline-info" type="submit">Sign Up</button>
    </div>
        </form>
    <div class="border-top pt-3">
          <small class="text-muted">
               Already Have An Account? <a class="ml-2" href="{% url 'login' %}"> Sign In</a>
          </small>
    </div>
    </div>

{% endblock content %}

House_Renting_Solver/users/templates/users/update.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
               
          <fieldset class="form-group">
              <legend class = "border-bottom mb-4">Update Your Profile </legend>
              {{ u_form | crispy }}
              {{ v_form | crispy }}
              {{ p_form | crispy }}
          </fieldset>
          <br>
    <div class="form-group">
       <button class ="btn btn-outline-info" type="submit">Update</button>
    </div>
        </form>
        <br>
   
    </div>

{% endblock content %}